# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]
nheight = np.array([69, 70, 71, 72, 73, 74, 75])
nweight = np.array([110, 120, 130, 140, 150, 160, 170])

bmi= nweight/(nheight**2) *730
bmi



array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [20]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass



def makeMatrix(a,b):
    return np.random.uniform(a,b,(6,5))
makeMatrix(3,5)



array([[3.04347315, 3.67486029, 4.7290337 , 4.23746198, 4.75450007],
       [4.28287665, 4.66424343, 4.23159573, 3.22983811, 4.73781118],
       [3.68894711, 4.20172557, 4.58209953, 3.87239837, 3.54844422],
       [4.57514284, 4.01129759, 3.72629196, 4.84598495, 4.66948572],
       [4.54510813, 4.002379  , 4.05266239, 3.32768992, 4.36470036],
       [4.01336273, 4.01408839, 3.53161039, 3.34113893, 3.9900002 ]])

### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [11]:
import csv
import numpy as np

#Test to make sure you have the correct data



In [16]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d=','):
    data = np.genfromtxt(filename, delimiter =d, skip_header =1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names= FIELDS, dtype=DATATYPES)
    return data
bs2017=load_data('../files/redsox_2017_hitting.txt')
bs2018=load_data('../files/redsox_2018_hitting.txt')

slg17=np.array(bs2017['SLG'])
slg17
slg18=np.array(bs2018['SLG'])
slg18

print(sum(slg17/len(slg17)))
print(sum(slg18/len(slg18)))
print(f'Boston 17 had higher SLG than Boston 18' )



0.39334782399237156
0.38749999925494194
Boston 17 had higher SLG than Boston 18
